### ISSUE TITLE
deploy functionality differs from video

### ISSUE THREAD

**Issue by cromestant** [apigee/Sweetlime#1]
Hello , looking at the video you have deploy functionality with apigeetools python script, however after cloning and testing I see the following error:

<pre>python: can't open file 'deploy.py': [Errno 2] No such file or directory
[Finished in 0.0s with exit code 2]
[cmd: ['python', '-u', 'deploy.py']]
[dir: /Users/cromestant/Codigos/apigee/app_advisor]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
</pre>

I have apigeetools installed in the $PATH variables so that it is accessible.
looking at the code it does not seem to be enabled this way.
was there a change?

[EDIT] 
other discrepancies with the video is the creation by default of the resources and policies directories.

**Comment by girishbr** [comment]
hi, thanks for using Sweetlime. What you reported was indeed a bug. The deploy.py file was inadvertently added to .gitignore. I have fixed this bug now. It should now work for you.

Can you explain your edit?
[EDIT]
other discrepancies with the video is the creation by default of the resources and policies directories.
Or you can also open another issue for this

**Comment by cromestant** [comment]
Sorry about the "bug" even if you allow deploy.py in the gitignore file, why would you need it? on the video you state you use apigeedeploy tool instead of the deploy.py
was it changed?

as for my edit On the video you also show new project created with all of the project folders (policies , directories, proxies and targets) however the default behavior only creates the last two . this is ok as when you add policies you get the other directories created.

**Comment by girishbr** [comment]
Nothing has changed. Sweetlime uses Apigeetool to deploy. But deploy.py acts as a bridge between Sweetlime and apigeetool. Deploy.py calls apigetool. 

```
apigeetool deployproxy -n $proxy -o $org -e $env -u $user -p $pass -d $dir 
```

**Comment by girishbr** [comment]
"as for my edit On the video you also show new project created with all of the project folders (policies , directories, proxies and targets) however the default behavior only creates the last two . this is ok as when you add policies you get the other directories created"

Create a new policy and choose the default folder - the policy as well as the policy folder gets created automatically.

**Comment by cromestant** [comment]
Ok so git pull updates and brings the deploy.py to the package folder . Now for existing projects is there something I should update as I still see the error ( so guessing it has not been copied to local project folder)? ( new to sublime so do not know all of the tricks). 
awesome plugin btw.

**Comment by girishbr** [comment]
Thanks!

Now for the existing projects.
Create a new dummy project with Sweetlime.
Just copy the deploy_vars.json and deploy.py from the newly created project into the existing one. That should do the trick.

**Comment by cromestant** [comment]
Thanks for the help and fix!
Will do just that, also do you accept feature requests or even better pull requests?

**Comment by girishbr** [comment]
Sure! Open for both feature reqs and pull reqs.Thanks for using SL!

**Comment by cromestant** [comment]
Sorry to reopen this,
but I'm recently trying to reuse this, and getting new error ( maybe
_yosemite_ related)
recloned the repo to see if any of my edits ( not pushed) were culprits,
but no.

found 11 files for base name Main.sublime-menu
reloading plugin Sweetlime.PolicyTemplates
reloading plugin Sweetlime.projectmaker
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py",
line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in
module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
  File "/Users/cromestant/Library/Application Support/Sublime Text
3/Packages/Sweetlime/projectmaker.py", line 4, in <module>
    from ApigeeSweetLime.configuration import ConfigurationReader
ImportError: No module named 'ApigeeSweetLime'

On Wed, May 7, 2014 at 11:57 AM, girishbr notifications@github.com wrote:

> Sure! Open for both feature reqs and pull reqs.Thanks for using SL!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apigee/Sweetlime/issues/1#issuecomment-42445787.

## 

MSc. Charles M. Romestant F.

Merci de penser à l'environnement avant d'imprimer cet e-mail
Please think about the environment before you print this e-mail
Por favor piense en el medio ambiente antes de imprimir este e-mail

**Comment by cromestant** [comment]
results in not being able to do "new proxy commnd"

On Fri, Jun 27, 2014 at 10:55 AM, Charles Romestant cromestant@gmail.com
wrote:

> Sorry to reopen this,
> but I'm recently trying to reuse this, and getting new error ( maybe
> _yosemite_ related)
> recloned the repo to see if any of my edits ( not pushed) were culprits,
> but no.
> 
> found 11 files for base name Main.sublime-menu
> reloading plugin Sweetlime.PolicyTemplates
> reloading plugin Sweetlime.projectmaker
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py",
> line 73, in reload_plugin
>     m = importlib.import_module(modulename)
>   File "X/importlib/**init**.py", line 88, in import_module
>   File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1525, in
> _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
>   File "<frozen importlib._bootstrap>", line 1023, in load_module
>   File "<frozen importlib._bootstrap>", line 1004, in load_module
>   File "<frozen importlib._bootstrap>", line 562, in
> module_for_loader_wrapper
>   File "<frozen importlib._bootstrap>", line 869, in _load_module
>   File "<frozen importlib._bootstrap>", line 313, in
> _call_with_frames_removed
>   File "/Users/cromestant/Library/Application Support/Sublime Text
> 3/Packages/Sweetlime/projectmaker.py", line 4, in <module>
>     from ApigeeSweetLime.configuration import ConfigurationReader
> ImportError: No module named 'ApigeeSweetLime'
> 
> On Wed, May 7, 2014 at 11:57 AM, girishbr notifications@github.com
> wrote:
> 
> > Sure! Open for both feature reqs and pull reqs.Thanks for using SL!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/apigee/Sweetlime/issues/1#issuecomment-42445787.
> 
> ## 
> 
> MSc. Charles M. Romestant F.
> 
> Merci de penser à l'environnement avant d'imprimer cet e-mail
> Please think about the environment before you print this e-mail
> Por favor piense en el medio ambiente antes de imprimir este e-mail

## 

MSc. Charles M. Romestant F.

Merci de penser à l'environnement avant d'imprimer cet e-mail
Please think about the environment before you print this e-mail
Por favor piense en el medio ambiente antes de imprimir este e-mail

**Comment by girishbr** [comment]
how did you clone? just git clone doesnt work. It has to be cloned to a specific directory.

git clone git@github.com:apigee/Sweetlime.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/ApigeeSweetLime

can you please confirm if you did that?

**Comment by cromestant** [comment]
ok camel case error, but still some deploying issues, apigeetool seems
broken atm.
will look futher

On Sun, Jun 29, 2014 at 9:56 AM, girishbr notifications@github.com wrote:

> how did you clone? just git clone doesnt work. It has to be cloned to a
> specific directory.
> 
> git clone git@github.com:apigee/Sweetlime.git ~/Library/Application\
> Support/Sublime\ Text\ 3/Packages/ApigeeSweetLime
> 
> can you please confirm if you did that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apigee/Sweetlime/issues/1#issuecomment-47455233.

## 

MSc. Charles M. Romestant F.

Merci de penser à l'environnement avant d'imprimer cet e-mail
Please think about the environment before you print this e-mail
Por favor piense en el medio ambiente antes de imprimir este e-mail
